Ext.define('app.Config', {
    alternateClassName: 'config',
    config:{
    	ctx: '',picCtx: '',webCtx: '',jsPath : '',extPath: '',imgPath: '',cssPath: '',fontPath: '',
	    user : {
	    	id:'1',ip:'',logintime:'',city:'',username:'',chianname:'',birthday:'',face:'',mobile:'',email:'',
	    	signature:'',role:'admin',score:20000,level:'50',roleId:'',modules:[],sessionId:'',userType:'',cityId:'',
	    	cityName:'',cityPinYin:'',siteId:'',companyId:'',companyType:'',departId:'',saleTraffic:0,saleRoute:0,
	    	departName:'',companyName:'',pid:'',oldDelayDay:'',oldAuditDay:'',shareRoute:'',isContractMust:'',isSetPayPassword:''
	    },
	    pageSize:50,
		moduleListUrl:{
			'b2b.user':'/b2b/user/list',
			'b2b.user.online':'/b2b/user/online/list',
			'b2b.module':'/b2b/module/list',
			'b2b.role':'/b2b/role/list',
			'b2b.ad':'/b2b/ad/list',
			'b2b.sms':'/b2b/sms/list',
			'b2b.notice':'/b2b/notice/list',
			'site.area':'/site/area/list',
			'account.list':'/account/list',
			'resource.traffic':'/resource/traffic/list',
			'produce.traffic':'/produce/traffic/list',
			'order.traffic':'/order/traffic/list',
			'resource.route':'/resource/route/list',
			'produce.route':'/produce/route/list',
			'order.route':'/order/route/list',
			'order.route.renew':'/order/route/renew/list',
			'finance.calc':'/finance/calc/list',
			'finance.pay':'/finance/pay/list',
			'b2c.shop':'/b2c/shop/list',
			'b2c.visitor':'/b2c/visitor/list',
			'b2c.member':'/b2c/member/list',
			'b2c.minishop':'/b2c/minishop/list',
			'b2c.setting':'/b2c/setting/list'
		},
		moduleAutoView:{
			/*配置后不使用通用BaseGrid展示*/
			'b2b.user.home':true,
			'b2b.user':true,
			'b2b.module':true,
			'b2b.role':true,
			'site.area':true,
			'site.setting':true,
			'site.company':true,
			'resource.traffic':true,
			'produce.traffic':true,
			'produce.route':true,
			'finance.calc':true,
			'finance.pay':true,
			'finance.query':true,
			'finance.alone':true,
			'account.index':true,
			'account.recharge':true,
			'stat.sale':true,
			'stat.sale.parent':true,
			'b2b.discount':true,
			'order.route.renew':true,
			'b2c.category':true,
			//'b2c.setting':true,
			'b2c.ad':true,
			'b2c.route':true
		},
		moduleAutoCondit:{
			/*配置后 使用查询条件 配置 需要在view下对应路径建立文件condit.js*/
			'order.traffic':true,
			'order.route':true
		},
		//有可能有变动 这里统一修改
		travelTools: ['其他','飞机','火车','动车','高铁','旅游车','轮船'],
		travelToolsIcon:['&#xe654;','&#xe656;','&#xe652;','&#xe650;','&#xe650;','&#xe64d;','&#xe64f;'],
		priceAttrs:{
			'0FA5123749CF8C87E050007F0100BCAD':'成人',
			'2D80E611DBA35261E050007F0100ED30':'儿童',
			'154E6C04C0C230E8E050007F010076E9':'不占床位/不含门票',
			'154E6C04C0C330E8E050007F010076E9':'不占床位/含门票',
			'154E6C04C0C430E8E050007F010076E9':'占床位/不含门票',
			'154E6C04C0C530E8E050007F010076E9':'占床位/含门票',
			'0FA5123749D18C87E050007F0100BCAD':'婴儿'
		},
		priceTypes:{'0FA5123749D28C87E050007F0100BCAD':'门市','0FA5123749D38C87E050007F0100BCAD':'同行'},
		routeAttrTagColor :{'':'#374046','品质':'#607d8b','自由行':'#4caf50','豪华':'#9c27b0','特价':'#ff5722','包机':'#3f51b5','纯玩':'#2196f3','自驾游':'#cddc39'},
		tpls:{
			visitor:{
				single:new Ext.XTemplate(
					'<div class="p-detail">',
			   			'<table width="100%" border="0">',
			    			'<tr>',
			    				'<td>姓名</td>',
			    				'<td>性别</td>',
			    				'<td>游客类型</td>',
			    				'<td>手机</td>',
			    				'<td>证件类型</td>',
			    				'<td>证件号码</td>',
			    			'</tr>',
			    			'<tpl for=".">',
			    			'<tr>',
			    				'<td>{NAME}</td>',
			    				'<td>{[values.SEX == 1 ? "男" : "女"]}</td>',
			    				'<td>{ATTR_NAME}</td>',
			    				'<td>{MOBILE}</td>',
			    				'<td>{CARD_TYPE}</td>',
			    				'<td>{CARD_NO}</td>',
			    			'</tr>',
			    			'</tpl>',
			    		'</table>',
			   		'</div>'
				),
				batch:new Ext.XTemplate(
					'<div class="p-detail">',
			   			'<table width="100%" border="0">',
			    			'<tr>',
			    				'<td class="name">产品名称</td>',
			    				'<td colspan="3">{PRODUCE_NAME}</td>',
			    				'<td class="name ">出发日期</td>',
			    				'<td>{START_DATE}</td>',
			    			'</tr>',
			    			'<tpl for="orders">',
			    			'<tr>',
			    				'<td class="name">订单编号</td>',
			    				'<td >{NO}</td>',
			    				'<td class="name">买家</td>',
			    				'<td>{BUY_COMPANY}</td>',
			    				'<td class="name ">电话</td>',
			    				'<td>{BUY_PHONE}</td>',
			    			'</tr>',
			    			'<tr>',
			    				'<td>姓名</td>',
			    				'<td>性别</td>',
			    				'<td>游客类型</td>',
			    				'<td>手机</td>',
			    				'<td>证件类型</td>',
			    				'<td>证件号码</td>',
			    			'</tr>',
			    			'<tpl for="vistors">',
			    			'<tr>',
			    				'<td>{NAME}</td>',
			    				'<td>{[values.SEX == 1 ? "男" : "女"]}</td>',
			    				'<td>{TYPE_NAME}</td>',
			    				'<td>{MOBILE}</td>',
			    				'<td>{CARD_TYPE}</td>',
			    				'<td>{CARD_NO}</td>',
			    			'</tr>',
			    			'</tpl>',
			    			'</tpl>',
			    		'</table>',
			   		'</div>'
				)
			},
			route:{}
		}
    },
    constructor :function(config){
    	this.initConfig(config);
    }
});